server:
  port: 8080

spring:
  application:
    name: payment-processor

azure:
  storage:
    queue:
      connection-string: ${AZURE_STORAGE}
      queue-name: orders
    blob:
      connection-string: ${AZURE_STORAGE}
  cosmos:
    endpoint: https://127.0.0.1:8081
    key: ${AZURE_COSMOS}
    database: TransactionsDB

audit:
  enabled: true

payment:
  processor:
    polling-interval-ms: 15000  # Cambiar a 10 minutos ahora esta en 15