spring:
  application:
    name: payment-processor

azure:
  storage:
    queue:
      connection-string: ${AZURE_STORAGE}
      queue-name: orders

  cosmos:
    endpoint: https://127.0.0.1:8081
    key: ${AZURE_COSMOS}
    database: TransactionsDB
    container: transactions
    consistency-level: SESSION
    populate-query-metrics: false
    connection-sharing-across-clients-enabled: false
    content-response-on-write-enabled: true
    endpoint-discovery-enabled: false
    read-requests-fallback-enabled: false

payment:
  processor:
    polling-interval-ms: 15000  # Revisa cola cada 15 segundos
    max-retries: 3
    retry-delay-ms: 1000